### PR TITLE
Add Grid localisation for acceleration.

### PR DESCRIPTION
**Pull request by Uswald**
Implementation of a cartesian grid which stores particles by cell. This is used to reduce the search of all couple of particles by considering only particles in the neighbour cells.

### CODE REVIEW

**Comment by ThomasCabaret** [comment]
Sure thanks!
(But keep in mind, as said in the readme, that this kind of feature is already implemented in alien with other very usefull features, in a way it would be a little "sad" to end up with particle system project duplicates)

**Comment by ThomasCabaret** [comment]
Hum in fact this is buggy (the behavior is not the same so for one reason or another something is messed up in the grid management).
(I'll temporarily fallback the PR as soon as I remember how to fallback PRs on github)

**Comment by Uswald** [comment]
In which way the behaviour is not the same?

**Comment by ThomasCabaret** [comment]
You do experiment 2 (see readme) and maybe various reset of the position within the same launch of the prog (R key) and checking unchecking the "destroy at boundary" option in the gui.  Doing that several times to setup vesicles for reproduction in a single program launch, it ends up with "stuck particles" or change in dynamics. (you can also use C key to toggle untoggle a usefull centerize behavior, easier to build vesicles with it,)

**Pull request merged**
